name: tasktroveprojects
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.16.0
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  firebase_storage: ^11.7.0
  shared_preferences: ^2.0.8
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.7
  intl: ^0.17.0
  flutter:
    sdk: flutter
  provider: ^6.1.2
  syncfusion_flutter_pdfviewer: ^20.4.54
  fl_chart: ^0.67.0
  smooth_page_indicator:
  uuid: ^3.0.7
  flutter_rating_bar: ^4.0.1
  lottie: ^3.0.0
  animated_splash_screen: ^1.3.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/tasktrovelogo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo_foreground.png"

  
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/categories/
    - assets/LibPic/
    - assets/animations/splash_screen.json
    - assets/animations/Loading.json
    - assets/pdf/AlgorithmsNotes.pdf
    - assets/pdf/Angular2Notes.pdf
    - assets/pdf/AngularJSNotes.pdf
    - assets/pdf/CNotes.pdf
    - assets/pdf/CSharpNotes.pdf
    - assets/pdf/CSSNotes.pdf
    - assets/pdf/EntityFrameworkNotes.pdf
    - assets/pdf/ExcelVBANotes.pdf
    - assets/pdf/GitNotes.pdf
    - assets/pdf/HaskellNotes.pdf
    - assets/pdf/HTML5CanvasNotes.pdf
    - assets/pdf/HTML5Notes.pdf
    - assets/pdf/JavaNotes.pdf
    - assets/pdf/jQueryNotes.pdf
    - assets/pdf/JavaLinuxNotes.pdf
    - assets/pdf/KotlinNotes.pdf
    - assets/pdf/LinuxNotes.pdf
    - assets/pdf/MATLABNotes.pdf
    - assets/pdf/MicrosoftSQLServerNotes.pdf
    - assets/pdf/MySQLNotes.pdf
    - assets/pdf/NodeJSNotes.pdf
    - assets/pdf/PerlNotes.pdf
    - assets/pdf/PHP.pdf
    - assets/pdf/PowerShellNotes.pdf
    - assets/pdf/ReactJSNotes.pdf
    - assets/pdf/ReactNativeNotes.pdf
    - assets/pdf/RubyNotes.pdf
    - assets/pdf/RubyOnRailsNotes.pdf
    - assets/pdf/SpringFrameworkNotes.pdf
    - assets/pdf/Sql.pdf
    - assets/pdf/TypeScriptNotes.pdf
    - assets/pdf/VBANotes.pdf
    - assets/pdf/VisualBasic_NETNotes.pdf
    - assets/pdf/XamarinFormsNotes.pdf
